### PR TITLE
Add libopengl0 to list of libraries

### LINKED ISSUE #61: possibly include opengl option
in superqt, I had this line:

```
      - name: Linux opengl
        if: runner.os == 'Linux' && ( startsWith(matrix.backend, 'pyside6') || startsWith(matrix.backend, 'pyqt6') )
        run: sudo apt-get install -y libopengl0 libegl1-mesa libxcb-xinput0
```

not sure if that's necessary still?  But could be a good option to add here

### PR DESCRIPTION
**Pull request by Czaki**
The lack of this library does not allow to switch to 3D rendering in napari. 

closes #61

### CODE REVIEW

**Comment by tlambert03** [comment]
thanks, note that this would close #61

**Comment by tlambert03** [comment]
do you also want to add `libegl1-mesa` as mentioned there?

**Comment by Czaki** [comment]
Here I need only to add `libopengl0` to get code working https://github.com/napari/napari/pull/6467/files#diff-b9d47163b1cf7210a86980d9d919fd325bb58eaf997d3c8a1e8e44359c6a9fbb

But mesa looks potentially useful. I may add it.

**Comment by tlambert03** [comment]
thanks!

**Comment by tlambert03** [comment]
released under v1.6 (and v1 updated to point to v1.6)

**Pull request merged**
